version: '3.6'
services:
  frontend:
    image: wampshark:latest
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        HTTPS_PROXY: $HTTPS_PROXY
        HTTP_PROXY: $HTTPS_PROXY
    dns:
      - 144.254.71.184
      - 171.70.168.183
    ports:
      - 8090:80